#include <stdio.h>
#include <math.h>
#include <time.h>
#include <stdlib.h>
#include <string.h>


int main(int argc, char* argv[]) { 


	char* posIn;
	int divisionsX,divisionsY,divisionsZ;
	float box[3];
	
	
	posIn = argv[1];
	sscanf(argv[2],"%d",&divisionsX); 
	sscanf(argv[3],"%d",&divisionsY);
	sscanf(argv[4],"%d",&divisionsZ);
	sscanf(argv[5],"%f",&box[0]);
	sscanf(argv[6],"%f",&box[1]);			//Box Dimension automatisch gewinnen ?!
	sscanf(argv[7],"%f",&box[2]);
	
	int npart,i,error;
	float posX,posY,posZ;
	int frames = 0;
	
	int* densityX = (int*) calloc(divisionsX,sizeof(int));
	int* densityY = (int*) calloc(divisionsY,sizeof(int));
	int* densityZ = (int*) calloc(divisionsZ,sizeof(int));
	
	
	FILE* xin = fopen(posIn,"r");
	
	fscanf(xin,"%d\n",&npart); //read number of particles
	fscanf(xin, "%*[^\n]\n", NULL);
	
	
	while( error!= EOF) { //Solange es noch etwas zu lesen gibt? 
		for(i=0; i<npart;i++) {
			fscanf(xin,"atom %f %f %f \n",&posX,&posY,&posZ);
			densityX[(int)(posX / (box[0] / divisionsX))] += 1; 
			densityY[(int)(posY / (box[1] / divisionsY))] += 1; 
			densityZ[(int)(posZ / (box[2] / divisionsZ))] += 1; 
		}
		frames++; //Hiermit dann mitzählen wie viele Frames abgelaufen - Am Ende die Dichte damit verrechnen und ausgeben
		fscanf(xin,"&d",&error) ;
	}
	
	FILE* dens = fopen("./densities.xyz","w");
	
	if(!dens) {
		printf("File not found!");
		exit(-1);
	}
	
	fprintf(dens,"%d\n",npart);
	fprintf(dens,"generated by my MD simulation\n");
	
	
	for(i=0; i<divisionsX; i++) {
		fprintf(dens, "Slab nr. %d %8.8f \n",i, (float)(densityX[i] / frames));
	}
	
	for(i=0; i<divisionsY; i++) {
		fprintf(dens, "%8.8f \n", (float)(densityY[i] / frames));
	}
	
	for(i=0; i<divisionsZ; i++) {
		fprintf(dens, "%8.8f \n", (float)(densityZ[i] / frames));
	}
	
}