#include <stdio.h>
#include <math.h>
#include <time.h>
#include <stdlib.h>
#include <string.h>

int main(int argc, char* argv[])
{

	float density,boxLength;
	float center[3];
	int partPerSide;
	int npart;

	int input=0;
	
	char* resPath;
	char* inPath;
		
	if(argc==7) {
		
			sscanf(argv[1],"%f",&density); //units: https://en.wikipedia.org/wiki/Lennard-Jones_potential#Dimensionless_.28reduced.29_units
			sscanf(argv[2],"%f",&boxLength);
			sscanf(argv[3],"%f",&center[0]);
			sscanf(argv[4],"%f",&center[1]);
			sscanf(argv[5],"%f",&center[2]);
			resPath = argv[6];
			printf("Input: Density: %f Box Length: %f CenterX: %f CenterY: %f CenterZ: %f Result: %s\n",density,boxLength,center[0],center[1], center[2], resPath);
		} else if(argc==8) {
			
			sscanf(argv[1],"%f",&density); //units: https://en.wikipedia.org/wiki/Lennard-Jones_potential#Dimensionless_.28reduced.29_units
			sscanf(argv[2],"%f",&boxLength);
			sscanf(argv[3],"%f",&center[0]);
			sscanf(argv[4],"%f",&center[1]);
			sscanf(argv[5],"%f",&center[2]);
			resPath = argv[6];
			inPath = argv[7];
			printf("Input: Density: %f Box Length: %f CenterX: %f CenterY: %f CenterZ: %f Result: %s Input: %s\n",density,boxLength,center[0],center[1], center[2], resPath, inPath);
			
			input=1;
		} else {
			
			printf("Arguments: <density> <boxLength> <CenterX> <CenterY> <CenterZ> <Path for result> (<Path for input Box>)\n");
			exit(-1);
		}
		
	partPerSide = (int)round(cbrtf(density)*boxLength);
	float dx = boxLength/partPerSide;
	center[0] += (dx -boxLength)/2;
	center[1] += (dx -boxLength)/2;
	center[2] += (dx -boxLength)/2;
	
	npart = partPerSide*partPerSide*partPerSide;
	
	FILE* out = fopen(resPath,"w");
	
	if(!out) {
		fprintf(stderr,"File %s not found!",resPath);
		exit(-1);
	}
	
	if(input) {
		FILE* in = fopen(inPath,"r");
		
		int inPart,i;
		float pos[3];
		
		if(!in) {
			fprintf(stderr,"File %s not found!",inPath);
			exit(-1);
		}
		
		fscanf(in,"%d\n",&inPart);
		//skip second line
		fscanf(in, "%*[^\n]\n", NULL);
		
		fprintf(out,"%d\n",npart+inPart);
		fprintf(out,"generated by the box initializer\n");
		
		for(i=0; i<inPart; i++) {
			fscanf(in, "atom %f %f %f\n",&pos[0],&pos[1],&pos[2]);
			fprintf(out, "atom %f %f %f\n",pos[0],pos[1],pos[2]);
		}
		fclose(in);
	} else {
		
		fprintf(out,"%d\n",npart);
		fprintf(out,"generated by the box initializer\n");
	}
	
	int i,j,k;
	
	for (i=0; i<partPerSide; i++)
		for(j=0; j<partPerSide; j++)
			for(k=0; k<partPerSide; k++)
				fprintf(out, "atom %f %f %f\n",k*dx +center[0],j*dx +center[1],i*dx +center[2]);

	fclose(out);
	
}
